package encryption;

import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Arrays;

/**
 * The class will create salts of 16 bytes, hash passwords and it has a method to 
 * compare input passwords with stored passwords
 *
 */
public class PasswordEncryption {
	
	private static final int ITERATIONS = 1042;
	
	/**
	 * Checks the inserted password against the hashed password.
	 * Works by encrypting the inputed password with the stored salt and
	 * comparing the result with the stored passwordhash.
	 * 
	 * @param password - The password inputed by the user.
	 * @param hashedPassword - The encrypted password stored in the database.
	 * @param salt - The salt stored in the database.
	 * @return boolean - True - The password matches. False - The password does not match.
	 */
	public static boolean checkPassword(String password, byte[] hashedPassword, byte[] salt){
		if(Arrays.equals(hashedPassword, getHash(password, salt))){
			return true;
		}
		else{
			return false;
		}
	}

	/**
	 * Creates a salt containing random bytes to be used with the hashing of password
	 * Returns an array with 16 random generated bytes.
	 * 
	 * @return byte[]
	 */
	public static byte[] createSalt(){
		byte[] salt = new byte[16];
		SecureRandom sr = new SecureRandom();
		sr.nextBytes(salt);
		return salt;
	}
	
	/**
	 * Generates the hashed password using the SHA-256 encryption
	 * 
	 * Returns an array of bytes containing the encrypted password.
	 * 
	 * @param password - The password to be encrypted
	 * @param salt - The salt
	 * @return byte[]
	 */
 	public static byte[] getHash(String password, byte[] salt){      	
 		byte[] passwordByte;
 		
        try { 	
        	MessageDigest digest = MessageDigest.getInstance("SHA-256");
        	digest.reset();
        	digest.update(salt);
        	passwordByte = digest.digest(password.getBytes("UTF-8"));
        	
        	for(int i = 0; i < ITERATIONS; i++){
        		digest.reset();
        		passwordByte = digest.digest(passwordByte);
        	}
        } 
        catch (Exception e) {
        	e.printStackTrace();
        	return null;
        }
        return passwordByte;
	}
}
